// STEP 1 -
//IMPORT STATEMENTS - import drift package
import 'package:drift/drift.dart';
// import generated file by drift
part 'drift_db.g.dart';

// STEP 2
//- Create table for data model
// name of auto generated data class will be class name with no s (Post)
// @DataClassName('CustomName') => would change the autogenerated class name
class Posts extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get content => text().nullable()();
  DateTimeColumn get date => dateTime().nullable()();
}

//STEP 3 -
//this annotation tells drift to prepare a database class that uses both of the
// tables we just defined.
@DriftDatabase(tables: [Posts])

//STEP 4 -
// Generating the code with dRIFT
class DriftDatabase extends _$DriftDataBase {}
